# Generated by Django 4.0.1 on 2022-01-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chasedae',
            name='dinner',
            field=models.TextField(null=True, verbose_name='석식'),
        ),
        migrations.AddField(
            model_name='chasedae',
            name='takeOut',
            field=models.TextField(null=True, verbose_name='TakeOut'),
        ),
        migrations.AlterField(
            model_name='chasedae',
            name='chef',
            field=models.TextField(null=True, verbose_name='셰프'),
        ),
        migrations.AlterField(
            model_name='chasedae',
            name='moms',
            field=models.TextField(null=True, verbose_name='맘스'),
        ),
        migrations.AlterField(
            model_name='chasedae',
            name='salad',
            field=models.TextField(null=True, verbose_name='샐러드'),
        ),
        migrations.AlterField(
            model_name='chasedae',
            name='special',
            field=models.TextField(null=True, verbose_name='정찬'),
        ),
    ]
