# Generated by Django 3.2.11 on 2022-02-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(choices=[('차세대', '차세대'), ('나노', '나노'), ('RDB', 'RDB')], default='차세대', max_length=10, verbose_name='식당')),
                ('table_img', models.ImageField(blank=True, null=True, upload_to='tables')),
                ('date', models.DateField(null=True, verbose_name='날짜')),
            ],
        ),
    ]
