# Generated by Django 3.2.11 on 2022-02-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0002_menutable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutable',
            name='table_img',
            field=models.ImageField(blank=True, null=True, upload_to='tables', verbose_name='식단표'),
        ),
    ]
