# Generated by Django 4.0.1 on 2022-01-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0002_chasedae_dinner_chasedae_takeout_alter_chasedae_chef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chasedae',
            name='date',
            field=models.DateField(null=True, verbose_name='날짜'),
        ),
    ]
