# Generated by Django 4.0.1 on 2022-01-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0003_chasedae_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chasedae',
            name='moms',
        ),
    ]
