# Generated by Django 3.2.11 on 2022-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0003_alter_menutable_table_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='chasedae',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='chasedae'),
        ),
        migrations.AddField(
            model_name='nano',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='nano'),
        ),
        migrations.AddField(
            model_name='rdb',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='rdb'),
        ),
    ]
