# Generated by Django 4.0.1 on 2022-01-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0004_remove_chasedae_moms'),
    ]

    operations = [
        migrations.AddField(
            model_name='chasedae',
            name='moms',
            field=models.TextField(null=True, verbose_name='맘스'),
        ),
    ]
