# Generated by Django 3.2.11 on 2022-02-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0004_auto_20220220_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chasedae',
            name='img',
        ),
        migrations.RemoveField(
            model_name='nano',
            name='img',
        ),
        migrations.RemoveField(
            model_name='rdb',
            name='img',
        ),
    ]
