# Generated by Django 4.0.1 on 2022-01-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0005_chasedae_moms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunchA', models.TextField(null=True, verbose_name='코스A')),
                ('lunchB', models.TextField(null=True, verbose_name='코스B')),
                ('plus', models.TextField(null=True, verbose_name='PLUS')),
                ('dinner', models.TextField(null=True, verbose_name='저녁')),
                ('date', models.DateField(null=True, verbose_name='날짜')),
            ],
        ),
        migrations.CreateModel(
            name='RDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korea', models.TextField(null=True, verbose_name='한식')),
                ('special', models.TextField(null=True, verbose_name='일품')),
                ('plus', models.TextField(null=True, verbose_name='플러스바')),
                ('dinner', models.TextField(null=True, verbose_name='저녁')),
                ('takeOut', models.TextField(null=True, verbose_name='TakeOut')),
                ('date', models.DateField(null=True, verbose_name='날짜')),
            ],
        ),
    ]
