# Generated by Django 3.2.11 on 2022-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0006_nano_rdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdb',
            name='plus',
        ),
        migrations.AddField(
            model_name='rdb',
            name='dinner_plus',
            field=models.TextField(null=True, verbose_name='저녁 플러스바'),
        ),
        migrations.AddField(
            model_name='rdb',
            name='lunch_plus',
            field=models.TextField(null=True, verbose_name='점심 플러스바'),
        ),
    ]
