# Generated by Django 4.0.1 on 2022-01-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaSeDae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moms', models.TextField(verbose_name='맘스')),
                ('chef', models.TextField(verbose_name='셰프')),
                ('special', models.TextField(verbose_name='정찬')),
                ('salad', models.TextField(verbose_name='샐러드')),
            ],
        ),
    ]
